collections:
  articles:
    relative_directory: _articles
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: _articles
      type: "posts"
    values:
      layout: "article"
      permalink: /article/:year-:month-:day-:title.html
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - LICENSE
  - README
  - vendor
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
    - node_modules/font-awesome/scss
    - fonts/source-code-pro
    - fonts/source-sans-pro
    - fonts/source-serif-pro
timezone: "America/Chicago"
