excerpt_separator: "<!-- more -->"
collections:
  games:
    relative_directory: _games
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: _games
      type: "games"
    values:
      layout: "game"
      permalink: /game/title.html
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - LICENSE
  - README
  - vendor
  - build.js
sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules/bootstrap/scss
    - node_modules/font-awesome/scss
    - fonts/source-code-pro
    - fonts/source-sans-pro
    - fonts/source-serif-pro
timezone: "America/Chicago"
